add functions and pytest
UBC-MDS/mini_tidy_python pull request #16
Opened 2019-02-14 01:30 UTC by lyiris22

- Add contents for function `my_gather` and `my_spread`
- Fix some test cases for `test_my_gather` and `test_my_spread`
- Add `setup.py`
- Add code, modify folder name and structure to run pytest

2019-02-14 01:45 UTC, ellognea commented on miniTidyPy/my_gather.py
> +# This is the script for function my_spread
I think you meant "This is the script for my function "my_gather"

2019-02-14 01:46 UTC, ellognea commented on miniTidyPy/my_gather.py
> +# Function left black at this point for further contributions
Can this be removed now that the function is defined ?

2019-02-14 02:03 UTC, ellognea requested changes
Great job Iris !  my_gather function has been neatly written. 
Just a few comment changes -- see comments.

2019-02-15 05:41 UTC, huijuechen commented on miniTidyPy/my_spread.py
> +    if key not in list(df):
Should we add message here? Something like "original df kept, did not get spread" (def more formal)? Sometimes df can contain many columns, might be difficult to check through all.

2019-02-15 05:43 UTC, huijuechen commented on miniTidyPy/my_spread.py
> +    if key not in list(df):
Overall structure looks clean!

2019-02-15 06:05 UTC, merged